# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='opt_info',
            fields=[
                ('mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('otp', models.PositiveSmallIntegerField(default=0, null=True)),
                ('flag', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
