# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Available', max_length=128)),
                ('description', models.CharField(default='Not Available', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='product_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('Ton', 'Ton'), ('Quintal', 'Quintal')], default='Ton', max_length=20)),
                ('image', models.CharField(default='', max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
    ]
