# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_data',
            name='category_id',
            field=models.IntegerField(default=0),
        ),
    ]
