# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_auto_20161229_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_data',
            name='image',
            field=models.ImageField(default='/media/product/default.png', upload_to='/product/'),
        ),
    ]
