# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_auto_20161229_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_data',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
