# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_category_data_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Ton', 'Ton'), ('Quintal', 'Quintal')], default='Ton', max_length=20)),
            ],
        ),
    ]
