# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_auto_20161229_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_data',
            name='unit',
            field=models.CharField(choices=[('Ton ( \u091f\u0928 )', 'Ton ( \u091f\u0928 )'), ('Quintal ( \u0915\u094d\u0935\u093f\u0902\u091f\u0932 )', 'Quintal ( \u0915\u094d\u0935\u093f\u0902\u091f\u0932 )')], default='Quintal ( \u0915\u094d\u0935\u093f\u0902\u091f\u0932 )', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit_data',
            name='name',
            field=models.CharField(choices=[('Ton ( \u091f\u0928 )', 'Ton ( \u091f\u0928 )'), ('Quintal ( \u0915\u094d\u0935\u093f\u0902\u091f\u0932 )', 'Quintal ( \u0915\u094d\u0935\u093f\u0902\u091f\u0932 )')], default='Quintal ( \u0915\u094d\u0935\u093f\u0902\u091f\u0932 )', max_length=20),
        ),
    ]
