# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('firm_name', models.CharField(max_length=240)),
                ('city', models.CharField(max_length=240)),
                ('mobile', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
