# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_user',
            name='catigory',
            field=models.CharField(default='buyer', max_length=120),
        ),
    ]
