# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sell_buy_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(default=0)),
                ('mobile', models.PositiveSmallIntegerField(default=0)),
                ('product_name', models.CharField(max_length=128)),
                ('product_description', models.CharField(max_length=255)),
                ('product_price', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('Ton ( \u091f\u0928 )', 'Ton ( \u091f\u0928 )'), ('Quintal ( \u0915\u094d\u0935\u093f\u0902\u091f\u0932 )', 'Quintal ( \u0915\u094d\u0935\u093f\u0902\u091f\u0932 )')], default='Quintal ( \u0915\u094d\u0935\u093f\u0902\u091f\u0932 )', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
