# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='version_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SmallIntegerField(default=0)),
                ('compulsory_update', models.BooleanField()),
            ],
        ),
    ]
