# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-01 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders_data',
            new_name='order_data',
        ),
    ]
